#!/bin/bash

NAME="apache-marina"
KEY="vockey"
SG_NAME="apache-sg"
REGION="us-east-1"

echo "Getting default VPC..."

VPC_ID=$(aws ec2 describe-vpcs \
--query "Vpcs[0].VpcId" \
--output text \
--region $REGION)

echo "Creating security group..."

SG_ID=$(aws ec2 create-security-group \
--group-name $SG_NAME \
--description "Apache Lab Security Group" \
--vpc-id $VPC_ID \
--query 'GroupId' \
--output text \
--region $REGION)

echo "Adding security group rules..."

aws ec2 authorize-security-group-ingress \
--group-id $SG_ID \
--protocol tcp \
--port 22 \
--cidr 0.0.0.0/0 \
--region $REGION

aws ec2 authorize-security-group-ingress \
--group-id $SG_ID \
--protocol tcp \
--port 80 \
--cidr 0.0.0.0/0 \
--region $REGION

aws ec2 authorize-security-group-ingress \
--group-id $SG_ID \
--protocol tcp \
--port 443 \
--cidr 0.0.0.0/0 \
--region $REGION


echo "Finding latest Ubuntu AMI..."

AMI_ID=$(aws ec2 describe-images \
--owners 099720109477 \
--filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
--query 'Images | sort_by(@, &CreationDate) | [-1].ImageId' \
--output text \
--region $REGION)

echo "Creating user data script..."

cat <<EOF > userdata.sh
#!/bin/bash
sudo apt update -y
sudo apt install apache2 -y
sudo systemctl enable apache2
sudo systemctl start apache2
EOF

echo "Launching instance..."

INSTANCE_ID=$(aws ec2 run-instances \
--image-id $AMI_ID \
--instance-type t2.micro \
--key-name $KEY \
--security-group-ids $SG_ID \
--user-data file://userdata.sh \
--tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$NAME}]" \
--query 'Instances[0].InstanceId' \
--output text \
--region $REGION)

echo "Waiting for instance to start..."

aws ec2 wait instance-running \
--instance-ids $INSTANCE_ID \
--region $REGION

PUBLIC_IP=$(aws ec2 describe-instances \
--instance-ids $INSTANCE_ID \
--query "Reservations[0].Instances[0].PublicIpAddress" \
--output text \
--region $REGION)

echo "Instance ready!"
echo "Instance ID: $INSTANCE_ID"
echo "Public IP: $PUBLIC_IP"
echo "Test Apache: http://$PUBLIC_IP"
